package com.example.MyProjectWithSecurity.data;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hibernate.annotations.Type;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "authors")
@ApiModel("data model of author entity")
public class Authors {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 1)
    private Integer id;
    @ApiModelProperty(value = "name of author", example = "Bob Morthon", position = 2)
    private String author;
    @JsonIgnore
    private String groupId;
    @Type(type = "text")
    //@JsonIgnore
    @ApiModelProperty(value="biography of author")
    private String biography;
    @ApiModelProperty(value ="url photo of author" )
    private String photo;

    @OneToMany(mappedBy = "author")
    @JsonIgnore
    private List<Book> bookList = new ArrayList<>();
    @OneToMany(mappedBy = "authors")
    @JsonIgnore
    private List<Book2Author>book2Authors = new ArrayList<>();

    public List<Book> getBookList(){
        return bookList;
    }

    public void setBookList(List<Book> bookList) {
        this.bookList = bookList;
    }

    public Authors(){

    }

    public Authors(Integer id, String author, String groupId, String biography, String photo, List<Book> bookList) {
        this.id = id;
        this.author = author;
        this.groupId = groupId;
        this.biography = biography;
        this.photo = photo;
        this.bookList = bookList;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getBiography() {
        return biography;
    }

    public void setBiography(String biography) {
        this.biography = biography;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    @Override
    public String toString() {
        return  author;
    }
}
