insert into document (slug, sort_index, text, title) values ('Finance', 92, 'Reverse-engineered systematic access', 'It');
insert into document (slug, sort_index, text, title) values ('Finance', 43, 'Multi-layered next generation archive', 'Ventosanzap');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 39, 'Mandatory 4th generation strategy', 'Kanlam');
insert into document (slug, sort_index, text, title) values ('Capital Goods', 4, 'Networked coherent parallelism', 'Lotlux');
insert into document (slug, sort_index, text, title) values ('n/a', 16, 'Synergized static hierarchy', 'Prodder');
insert into document (slug, sort_index, text, title) values ('Public Utilities', 71, 'Advanced multimedia data-warehouse', 'Zamit');
insert into document (slug, sort_index, text, title) values ('Capital Goods', 97, 'Optional actuating adapter', 'Treeflex');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 5, 'Configurable leading edge structure', 'Mat Lam Tam');
insert into document (slug, sort_index, text, title) values ('Health Care', 53, 'Optional bifurcated function', 'Alphazap');
insert into document (slug, sort_index, text, title) values ('n/a', 89, 'Open-source background frame', 'Alpha');
insert into document (slug, sort_index, text, title) values ('Finance', 62, 'Open-architected 24/7 system engine', 'Konklux');
insert into document (slug, sort_index, text, title) values ('Consumer Non-Durables', 27, 'Enterprise-wide fault-tolerant emulation', 'Gembucket');
insert into document (slug, sort_index, text, title) values ('n/a', 98, 'Front-line intermediate structure', 'Wrapsafe');
insert into document (slug, sort_index, text, title) values ('Finance', 92, 'Future-proofed logistical collaboration', 'Holdlamis');
insert into document (slug, sort_index, text, title) values ('Consumer Non-Durables', 37, 'Configurable system-worthy support', 'Holdlamis');
insert into document (slug, sort_index, text, title) values ('Consumer Durables', 76, 'Pre-emptive dynamic interface', 'Cookley');
insert into document (slug, sort_index, text, title) values ('Health Care', 14, 'Front-line system-worthy matrix', 'Lotstring');
insert into document (slug, sort_index, text, title) values ('Health Care', 57, 'Re-contextualized static extranet', 'Asoka');
insert into document (slug, sort_index, text, title) values ('Health Care', 56, 'Monitored 5th generation concept', 'Zamit');
insert into document (slug, sort_index, text, title) values ('Finance', 3, 'Exclusive reciprocal adapter', 'Rank');
insert into document (slug, sort_index, text, title) values ('Health Care', 16, 'Synergistic impactful matrix', 'Cardguard');
insert into document (slug, sort_index, text, title) values ('Consumer Durables', 82, 'Grass-roots tertiary concept', 'Fix San');
insert into document (slug, sort_index, text, title) values ('Technology', 50, 'Diverse transitional strategy', 'Bitwolf');
insert into document (slug, sort_index, text, title) values ('n/a', 36, 'Versatile multi-state budgetary management', 'Bamity');
insert into document (slug, sort_index, text, title) values ('Technology', 12, 'Organic methodical function', 'Trippledex');
insert into document (slug, sort_index, text, title) values ('Health Care', 28, 'Seamless 24/7 model', 'Toughjoyfax');
insert into document (slug, sort_index, text, title) values ('Finance', 77, 'Quality-focused incremental installation', 'Bigtax');
insert into document (slug, sort_index, text, title) values ('Capital Goods', 12, 'Face to face local ability', 'Transcof');
insert into document (slug, sort_index, text, title) values ('Finance', 10, 'Multi-layered scalable website', 'Redhold');
insert into document (slug, sort_index, text, title) values ('Technology', 10, 'Optimized regional data-warehouse', 'Hatity');
insert into document (slug, sort_index, text, title) values ('Finance', 92, 'Vision-oriented user-facing instruction set', 'Greenlam');
insert into document (slug, sort_index, text, title) values ('n/a', 4, 'Secured next generation approach', 'Cardguard');
insert into document (slug, sort_index, text, title) values ('n/a', 46, 'Multi-lateral reciprocal interface', 'Zaam-Dox');
insert into document (slug, sort_index, text, title) values ('Finance', 9, 'Synergized asynchronous hierarchy', 'Aerified');
insert into document (slug, sort_index, text, title) values ('n/a', 92, 'Customer-focused bottom-line groupware', 'Bitchip');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 17, 'Business-focused multi-tasking infrastructure', 'Ronstring');
insert into document (slug, sort_index, text, title) values ('n/a', 2, 'Open-architected composite time-frame', 'Konklux');
insert into document (slug, sort_index, text, title) values ('n/a', 68, 'Focused client-server open system', 'Zamit');
insert into document (slug, sort_index, text, title) values ('Technology', 100, 'User-centric hybrid approach', 'Gembucket');
insert into document (slug, sort_index, text, title) values ('Technology', 71, 'Open-architected 6th generation capacity', 'Namfix');
insert into document (slug, sort_index, text, title) values ('Health Care', 74, 'Integrated tangible installation', 'Viva');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 26, 'Optional non-volatile focus group', 'Konklab');
insert into document (slug, sort_index, text, title) values ('Finance', 81, 'Seamless directional service-desk', 'Zaam-Dox');
insert into document (slug, sort_index, text, title) values ('Energy', 64, 'Organic executive core', 'Lotlux');
insert into document (slug, sort_index, text, title) values ('Consumer Non-Durables', 1, 'Function-based 24/7 productivity', 'Prodder');
insert into document (slug, sort_index, text, title) values ('Basic Industries', 47, 'Ergonomic context-sensitive approach', 'Viva');
insert into document (slug, sort_index, text, title) values ('Basic Industries', 22, 'Secured solution-oriented emulation', 'Andalax');
insert into document (slug, sort_index, text, title) values ('Miscellaneous', 94, 'Pre-emptive needs-based forecast', 'Fintone');
insert into document (slug, sort_index, text, title) values ('Public Utilities', 69, 'User-friendly heuristic portal', 'Voyatouch');
insert into document (slug, sort_index, text, title) values ('Health Care', 33, 'Open-architected methodical contingency', 'Zaam-Dox');
insert into document (slug, sort_index, text, title) values ('n/a', 91, 'Self-enabling impactful support', 'Tres-Zap');
insert into document (slug, sort_index, text, title) values ('Finance', 15, 'Synergistic global analyzer', 'Cookley');
insert into document (slug, sort_index, text, title) values ('Health Care', 72, 'De-engineered transitional artificial intelligence', 'Alphazap');
insert into document (slug, sort_index, text, title) values ('Basic Industries', 92, 'Multi-lateral composite policy', 'Sonsing');
insert into document (slug, sort_index, text, title) values ('Finance', 21, 'Public-key 6th generation process improvement', 'Tresom');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 16, 'Exclusive regional superstructure', 'Bigtax');
insert into document (slug, sort_index, text, title) values ('Finance', 34, 'Focused tertiary policy', 'Flowdesk');
insert into document (slug, sort_index, text, title) values ('Consumer Non-Durables', 2, 'Progressive well-modulated workforce', 'Bamity');
insert into document (slug, sort_index, text, title) values ('n/a', 17, 'Mandatory client-driven product', 'Flexidy');
insert into document (slug, sort_index, text, title) values ('Finance', 11, 'Universal value-added website', 'Zathin');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 44, 'Implemented value-added emulation', 'Job');
insert into document (slug, sort_index, text, title) values ('Technology', 93, 'Pre-emptive value-added neural-net', 'Matsoft');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 68, 'Cross-platform object-oriented frame', 'Andalax');
insert into document (slug, sort_index, text, title) values ('Health Care', 29, 'Quality-focused grid-enabled moratorium', 'Duobam');
insert into document (slug, sort_index, text, title) values ('n/a', 93, 'Persistent explicit definition', 'Fintone');
insert into document (slug, sort_index, text, title) values ('Miscellaneous', 16, 'Enterprise-wide well-modulated firmware', 'Duobam');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 62, 'Inverse asynchronous help-desk', 'Asoka');
insert into document (slug, sort_index, text, title) values ('Capital Goods', 14, 'Distributed cohesive service-desk', 'Lotstring');
insert into document (slug, sort_index, text, title) values ('Basic Industries', 10, 'Phased multi-tasking customer loyalty', 'Biodex');
insert into document (slug, sort_index, text, title) values ('n/a', 58, 'Automated multi-tasking portal', 'Opela');
insert into document (slug, sort_index, text, title) values ('Basic Industries', 85, 'Advanced intangible synergy', 'Konklab');
insert into document (slug, sort_index, text, title) values ('Health Care', 96, 'Pre-emptive 4th generation superstructure', 'Domainer');
insert into document (slug, sort_index, text, title) values ('Finance', 83, 'Ergonomic actuating toolset', 'Zathin');
insert into document (slug, sort_index, text, title) values ('Health Care', 17, 'Networked methodical system engine', 'Zontrax');
insert into document (slug, sort_index, text, title) values ('n/a', 31, 'Re-contextualized zero administration knowledge user', 'Cookley');
insert into document (slug, sort_index, text, title) values ('Finance', 39, 'Distributed contextually-based instruction set', 'Alphazap');
insert into document (slug, sort_index, text, title) values ('Capital Goods', 5, 'Configurable homogeneous artificial intelligence', 'Gembucket');
insert into document (slug, sort_index, text, title) values ('Energy', 96, 'Enhanced actuating installation', 'Greenlam');
insert into document (slug, sort_index, text, title) values ('Finance', 48, 'Fully-configurable 5th generation artificial intelligence', 'Bitwolf');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 89, 'Universal even-keeled success', 'Sub-Ex');
insert into document (slug, sort_index, text, title) values ('n/a', 63, 'Multi-lateral intangible hierarchy', 'Fintone');
insert into document (slug, sort_index, text, title) values ('Capital Goods', 36, 'Public-key incremental knowledge base', 'Quo Lux');
insert into document (slug, sort_index, text, title) values ('Finance', 74, 'Polarised clear-thinking architecture', 'Latlux');
insert into document (slug, sort_index, text, title) values ('Health Care', 2, 'Cross-platform next generation implementation', 'Zathin');
insert into document (slug, sort_index, text, title) values ('n/a', 57, 'Multi-tiered neutral model', 'Transcof');
insert into document (slug, sort_index, text, title) values ('n/a', 64, 'Triple-buffered directional help-desk', 'Wrapsafe');
insert into document (slug, sort_index, text, title) values ('n/a', 21, 'Realigned dynamic core', 'Vagram');
insert into document (slug, sort_index, text, title) values ('Technology', 65, 'Persistent reciprocal synergy', 'Ronstring');
insert into document (slug, sort_index, text, title) values ('Consumer Services', 68, 'Open-source neutral extranet', 'Y-Solowarm');
insert into document (slug, sort_index, text, title) values ('Miscellaneous', 71, 'Integrated impactful forecast', 'Opela');
insert into document (slug, sort_index, text, title) values ('Technology', 74, 'Diverse intermediate portal', 'Otcom');
insert into document (slug, sort_index, text, title) values ('n/a', 57, 'Pre-emptive exuding throughput', 'Pannier');
insert into document (slug, sort_index, text, title) values ('Transportation', 87, 'Reverse-engineered 24 hour middleware', 'Subin');
insert into document (slug, sort_index, text, title) values ('Health Care', 68, 'Extended non-volatile hierarchy', 'Daltfresh');
insert into document (slug, sort_index, text, title) values ('Public Utilities', 60, 'Grass-roots uniform array', 'Duobam');
insert into document (slug, sort_index, text, title) values ('n/a', 81, 'Automated upward-trending pricing structure', 'Redhold');
insert into document (slug, sort_index, text, title) values ('Technology', 28, 'Versatile empowering policy', 'Vagram');
insert into document (slug, sort_index, text, title) values ('Technology', 83, 'Re-contextualized explicit alliance', 'Andalax');
insert into document (slug, sort_index, text, title) values ('Technology', 60, 'Sharable multi-state encryption', 'Sub-Ex');
insert into document (slug, sort_index, text, title) values ('Finance', 29, 'Reactive coherent encoding', 'Voyatouch');
