insert into fag (sort_index, answer, question) values (68, 'Reduced zero tolerance alliance', 'Synergized coherent forecast');
insert into fag (sort_index, answer, question) values (36, 'Visionary systematic software', 'Profound foreground conglomeration');
insert into fag (sort_index, answer, question) values (24, 'Customer-focused needs-based knowledge base', 'Upgradable incremental core');
insert into fag (sort_index, answer, question) values (62, 'Integrated motivating neural-net', 'Profit-focused system-worthy service-desk');
insert into fag (sort_index, answer, question) values (58, 'Pre-emptive attitude-oriented success', 'Secured foreground intranet');
insert into fag (sort_index, answer, question) values (23, 'Re-engineered multi-tasking system engine', 'Intuitive dynamic workforce');
insert into fag (sort_index, answer, question) values (60, 'Assimilated fault-tolerant intranet', 'Total holistic core');
insert into fag (sort_index, answer, question) values (35, 'Proactive stable superstructure', 'Innovative coherent project');
insert into fag (sort_index, answer, question) values (34, 'Monitored actuating moderator', 'Triple-buffered global attitude');
insert into fag (sort_index, answer, question) values (70, 'Distributed tangible solution', 'Robust logistical leverage');
insert into fag (sort_index, answer, question) values (34, 'Optional transitional project', 'Integrated intangible website');
insert into fag (sort_index, answer, question) values (65, 'Face to face fault-tolerant core', 'Switchable bifurcated superstructure');
insert into fag (sort_index, answer, question) values (62, 'Face to face grid-enabled infrastructure', 'Adaptive reciprocal hub');
insert into fag (sort_index, answer, question) values (53, 'De-engineered local moratorium', 'Re-contextualized holistic superstructure');
insert into fag (sort_index, answer, question) values (26, 'Proactive 24 hour budgetary management', 'Optimized local strategy');
insert into fag (sort_index, answer, question) values (5, 'Cloned next generation hub', 'Robust next generation projection');
insert into fag (sort_index, answer, question) values (19, 'Ergonomic bandwidth-monitored Graphic Interface', 'Phased multi-tasking capacity');
insert into fag (sort_index, answer, question) values (81, 'Re-contextualized heuristic function', 'Secured web-enabled benchmark');
insert into fag (sort_index, answer, question) values (97, 'Digitized homogeneous service-desk', 'De-engineered zero defect archive');
insert into fag (sort_index, answer, question) values (22, 'Future-proofed bifurcated instruction set', 'Devolved regional conglomeration');
insert into fag (sort_index, answer, question) values (80, 'Vision-oriented asynchronous algorithm', 'Adaptive interactive attitude');
insert into fag (sort_index, answer, question) values (70, 'Face to face logistical framework', 'Grass-roots multi-tasking function');
insert into fag (sort_index, answer, question) values (78, 'Decentralized user-facing access', 'Centralized modular parallelism');
insert into fag (sort_index, answer, question) values (25, 'Reactive needs-based local area network', 'Digitized systematic approach');
insert into fag (sort_index, answer, question) values (19, 'Fully-configurable empowering knowledge base', 'Mandatory cohesive service-desk');
insert into fag (sort_index, answer, question) values (50, 'Versatile human-resource migration', 'Monitored asymmetric budgetary management');
insert into fag (sort_index, answer, question) values (34, 'Advanced demand-driven matrices', 'Organic eco-centric contingency');
insert into fag (sort_index, answer, question) values (69, 'Diverse coherent utilisation', 'Total 5th generation leverage');
insert into fag (sort_index, answer, question) values (63, 'Decentralized web-enabled analyzer', 'Mandatory full-range collaboration');
insert into fag (sort_index, answer, question) values (60, 'Switchable system-worthy open system', 'Organized homogeneous standardization');
insert into fag (sort_index, answer, question) values (88, 'Inverse explicit model', 'Vision-oriented mobile initiative');
insert into fag (sort_index, answer, question) values (60, 'Vision-oriented multi-tasking focus group', 'Right-sized interactive project');
insert into fag (sort_index, answer, question) values (13, 'Public-key zero tolerance definition', 'Object-based demand-driven collaboration');
insert into fag (sort_index, answer, question) values (17, 'User-centric 24/7 algorithm', 'Self-enabling zero administration adapter');
insert into fag (sort_index, answer, question) values (5, 'Realigned web-enabled framework', 'Grass-roots 24 hour Graphic Interface');
insert into fag (sort_index, answer, question) values (82, 'Seamless contextually-based info-mediaries', 'Organized scalable algorithm');
insert into fag (sort_index, answer, question) values (25, 'Cross-platform impactful extranet', 'Focused bifurcated migration');
insert into fag (sort_index, answer, question) values (60, 'Implemented transitional frame', 'Implemented interactive concept');
insert into fag (sort_index, answer, question) values (66, 'Optimized multi-tasking functionalities', 'Intuitive intermediate local area network');
insert into fag (sort_index, answer, question) values (42, 'Assimilated cohesive strategy', 'Cloned contextually-based solution');
insert into fag (sort_index, answer, question) values (16, 'Enhanced analyzing customer loyalty', 'Business-focused transitional instruction set');
insert into fag (sort_index, answer, question) values (95, 'Innovative attitude-oriented access', 'Open-source bifurcated initiative');
insert into fag (sort_index, answer, question) values (47, 'Fully-configurable transitional secured line', 'Multi-channelled intangible open architecture');
insert into fag (sort_index, answer, question) values (55, 'Down-sized systemic core', 'Persevering static time-frame');
insert into fag (sort_index, answer, question) values (70, 'Realigned empowering parallelism', 'Mandatory context-sensitive hardware');
insert into fag (sort_index, answer, question) values (57, 'Future-proofed multimedia groupware', 'Proactive multi-tasking complexity');
insert into fag (sort_index, answer, question) values (60, 'Cloned asynchronous website', 'Self-enabling web-enabled internet solution');
insert into fag (sort_index, answer, question) values (5, 'Synergized needs-based local area network', 'Reduced stable instruction set');
insert into fag (sort_index, answer, question) values (66, 'Vision-oriented disintermediate model', 'Enhanced scalable workforce');
insert into fag (sort_index, answer, question) values (81, 'Face to face empowering archive', 'Progressive even-keeled pricing structure');
insert into fag (sort_index, answer, question) values (18, 'Quality-focused discrete function', 'Upgradable 24/7 array');
insert into fag (sort_index, answer, question) values (69, 'Business-focused real-time emulation', 'Profound needs-based challenge');
insert into fag (sort_index, answer, question) values (18, 'Multi-lateral systematic service-desk', 'Ergonomic uniform utilisation');
insert into fag (sort_index, answer, question) values (29, 'Vision-oriented multimedia application', 'Vision-oriented reciprocal productivity');
insert into fag (sort_index, answer, question) values (48, 'Reduced attitude-oriented protocol', 'Profound systemic instruction set');
insert into fag (sort_index, answer, question) values (69, 'Ameliorated content-based hierarchy', 'Synchronised tertiary task-force');
insert into fag (sort_index, answer, question) values (34, 'User-centric client-driven artificial intelligence', 'Customer-focused client-driven database');
insert into fag (sort_index, answer, question) values (70, 'Function-based local intranet', 'Total 6th generation product');
insert into fag (sort_index, answer, question) values (18, 'Extended national parallelism', 'Digitized cohesive paradigm');
insert into fag (sort_index, answer, question) values (8, 'Synergistic 24/7 standardization', 'Profit-focused leading edge protocol');
insert into fag (sort_index, answer, question) values (75, 'Implemented 3rd generation installation', 'Managed incremental encryption');
insert into fag (sort_index, answer, question) values (4, 'Profound 3rd generation help-desk', 'Front-line composite methodology');
insert into fag (sort_index, answer, question) values (88, 'Open-architected modular portal', 'Exclusive coherent knowledge base');
insert into fag (sort_index, answer, question) values (80, 'Seamless motivating knowledge user', 'Down-sized regional local area network');
insert into fag (sort_index, answer, question) values (97, 'Down-sized 24 hour knowledge user', 'Assimilated well-modulated circuit');
insert into fag (sort_index, answer, question) values (25, 'Devolved 24 hour conglomeration', 'User-friendly leading edge workforce');
insert into fag (sort_index, answer, question) values (1, 'Persevering national emulation', 'Cross-platform 6th generation initiative');
insert into fag (sort_index, answer, question) values (81, 'Enhanced discrete utilisation', 'Centralized cohesive software');
insert into fag (sort_index, answer, question) values (61, 'Virtual intangible help-desk', 'Optimized even-keeled extranet');
insert into fag (sort_index, answer, question) values (56, 'Quality-focused leading edge internet solution', 'Managed clear-thinking challenge');
insert into fag (sort_index, answer, question) values (35, 'Mandatory didactic matrices', 'Inverse dedicated knowledge base');
insert into fag (sort_index, answer, question) values (97, 'Multi-channelled 24/7 process improvement', 'Focused systemic initiative');
insert into fag (sort_index, answer, question) values (19, 'Polarised dedicated local area network', 'Mandatory needs-based info-mediaries');
insert into fag (sort_index, answer, question) values (5, 'Cloned uniform intranet', 'Realigned next generation conglomeration');
insert into fag (sort_index, answer, question) values (41, 'Progressive stable function', 'Right-sized fresh-thinking hierarchy');
insert into fag (sort_index, answer, question) values (76, 'Advanced web-enabled local area network', 'Adaptive multi-state paradigm');
insert into fag (sort_index, answer, question) values (91, 'Multi-channelled well-modulated moratorium', 'Right-sized attitude-oriented Graphical User Interface');
insert into fag (sort_index, answer, question) values (37, 'Phased bifurcated info-mediaries', 'Cross-platform leading edge array');
insert into fag (sort_index, answer, question) values (94, 'Team-oriented asymmetric orchestration', 'Object-based systematic software');
insert into fag (sort_index, answer, question) values (5, 'De-engineered national initiative', 'Expanded non-volatile capability');
insert into fag (sort_index, answer, question) values (2, 'Multi-tiered 4th generation infrastructure', 'Triple-buffered fault-tolerant knowledge base');
insert into fag (sort_index, answer, question) values (55, 'Distributed intermediate hardware', 'Customizable mission-critical support');
insert into fag (sort_index, answer, question) values (48, 'Decentralized systemic collaboration', 'Profound multi-tasking capability');
insert into fag (sort_index, answer, question) values (44, 'Ameliorated human-resource analyzer', 'Self-enabling upward-trending implementation');
insert into fag (sort_index, answer, question) values (82, 'Customizable holistic info-mediaries', 'Implemented modular leverage');
insert into fag (sort_index, answer, question) values (58, 'Persevering heuristic hierarchy', 'Object-based executive knowledge user');
insert into fag (sort_index, answer, question) values (75, 'Optional analyzing support', 'Object-based non-volatile matrix');
insert into fag (sort_index, answer, question) values (31, 'Profit-focused fresh-thinking solution', 'Visionary needs-based archive');
insert into fag (sort_index, answer, question) values (43, 'Distributed methodical model', 'Switchable logistical project');
insert into fag (sort_index, answer, question) values (60, 'Pre-emptive context-sensitive throughput', 'Organized dedicated encryption');
insert into fag (sort_index, answer, question) values (82, 'User-centric interactive function', 'Cross-group value-added adapter');
insert into fag (sort_index, answer, question) values (96, 'Programmable reciprocal flexibility', 'Business-focused full-range superstructure');
insert into fag (sort_index, answer, question) values (21, 'Virtual bottom-line frame', 'Synchronised solution-oriented algorithm');
insert into fag (sort_index, answer, question) values (31, 'Persistent static forecast', 'Multi-channelled even-keeled projection');
insert into fag (sort_index, answer, question) values (93, 'Sharable stable initiative', 'Synergized demand-driven instruction set');
insert into fag (sort_index, answer, question) values (99, 'Exclusive intangible core', 'Ameliorated asynchronous moderator');
insert into fag (sort_index, answer, question) values (53, 'Balanced methodical pricing structure', 'Networked explicit interface');
insert into fag (sort_index, answer, question) values (57, 'Managed homogeneous Graphical User Interface', 'Front-line dedicated support');
insert into fag (sort_index, answer, question) values (90, 'Managed fresh-thinking workforce', 'Automated real-time contingency');
insert into fag (sort_index, answer, question) values (18, 'De-engineered impactful project', 'Fundamental client-driven monitoring');
