insert into genre(name,parent_id,slug) values ('Легкое чтение',0,'l_ch');
insert into genre(name,parent_id,slug) values ('Фантастика',1,'ph');
insert into genre(name,parent_id,slug) values ('Боевики',1,'boevik');
insert into genre(name,parent_id,slug) values ('Детективы',1,'l_ch');
insert into genre(name,parent_id,slug) values ('Триллер',4,'l_ch');
insert into genre(name,parent_id,slug) values ('Крутой детектив',4,'l_ch');
insert into genre(name,parent_id,slug) values ('Иронический детектив',4,'l_ch');
insert into genre(name,parent_id,slug) values ('Про маньяков',4,'l_ch');
insert into genre(name,parent_id,slug) values ('Шпионский детектив',4,'l_ch');
insert into genre(name,parent_id,slug) values ('Криминальный детектив',4,'l_ch');
insert into genre(name,parent_id,slug) values ('Классический детектив',4,'l_ch');
insert into genre(name,parent_id,slug) values ('Политический детектив',4,'l_ch');
insert into genre(name,parent_id,slug) values ('Фэнтези',1,'l_ch');
insert into genre(name,parent_id,slug) values ('Романы',1,'l_ch');
insert into genre(name,parent_id,slug) values ('Ужасы',1,'l_ch');
insert into genre(name,parent_id,slug) values ('Приключения',1,'l_ch');
insert into genre(name,parent_id,slug) values ('Серьезное чтение',0,'l_ch');
insert into genre(name,parent_id,slug) values ('Биографии',17,'l_ch');
insert into genre(name,parent_id,slug) values ('Деловая литература',0,'l_ch');
insert into genre(name,parent_id,slug) values ('Деловая литература',19,'l_ch');
insert into genre(name,parent_id,slug) values ('Управление экономикой',19,'l_ch');
insert into genre(name,parent_id,slug) values ('Финансы',19,'l_ch');
insert into genre(name,parent_id,slug) values ('Интернет-бизнес',19,'l_ch');
