insert into tegs(idteg, tegname)values (1, 'современная литература');
insert into tegs(idteg, tegname)values (2,'классическая литература');
insert into tegs(idteg, tegname)values (3,'зарубежная литература');
insert into tegs(idteg, tegname)values (4,'фэнтези');
insert into tegs(idteg, tegname)values (5,'английская литература');
insert into tegs(idteg, tegname)values (6,'русская литература');
insert into tegs(idteg, tegname)values (7,'американская литература');
insert into tegs(idteg, tegname)values (8,'фантастика');
insert into tegs(idteg, tegname)values (9,'детская литература');
insert into tegs(idteg, tegname)values (10,'детектив');
insert into tegs(idteg, tegname)values (11,'любовь');
insert into tegs(idteg, tegname)values (12,'мистика');
insert into tegs(idteg, tegname)values (13,'юмор');
insert into tegs(idteg, tegname)values (14,'приключения');
insert into tegs(idteg, tegname)values (15,'сказка');
insert into tegs(idteg, tegname)values (16,'французская литература');
insert into tegs(idteg, tegname)values (17,'художественная литература');
insert into tegs(idteg, tegname)values (18,'психология');
insert into tegs(idteg, tegname)values (19,'философия');
insert into tegs(idteg, tegname)values (20,'экранизировано');
insert into tegs(idteg, tegname)values (21,'любимое');
insert into tegs(idteg, tegname)values (22,'антиутопия');
insert into tegs(idteg, tegname)values (23,'books you must read before you die');
insert into tegs(idteg, tegname)values (24,'роман');
insert into tegs(idteg, tegname)values (25,'франция');
insert into tegs(idteg, tegname)values (26,'дайте две');
insert into tegs(idteg, tegname)values (27,'young adult');
insert into tegs(idteg, tegname)values (28,'война');
insert into tegs(idteg, tegname)values (29,'история');
insert into tegs(idteg, tegname)values (30,'флэшмоб 2016');
insert into tegs(idteg, tegname)values (31,'детство');
insert into tegs(idteg, tegname)values (32,'жизнь');
insert into tegs(idteg, tegname)values (33,'драма');
insert into tegs(idteg, tegname)values (34,'россия');
insert into tegs(idteg, tegname)values (35,'книжное путешествие');
insert into tegs(idteg, tegname)values (36,'советская литература');
insert into tegs(idteg, tegname)values (37,'триллер');
insert into tegs(idteg, tegname)values (38,'америка');
insert into tegs(idteg, tegname)values (39,'немецкая литература');
insert into tegs(idteg, tegname)values (40,'вампиры');
insert into tegs(idteg, tegname)values (41,'школьная программа');
insert into tegs(idteg, tegname)values (42,'рассказы');
insert into tegs(idteg, tegname)values (43,'магия');
insert into tegs(idteg, tegname)values (44,'дети');
insert into tegs(idteg, tegname)values (45,'русская классика');
insert into tegs(idteg, tegname)values (46,'флэшмоб 2015');
insert into tegs(idteg, tegname)values (47,'биография');
insert into tegs(idteg, tegname)values (48,'english');
insert into tegs(idteg, tegname)values (49,'france');
insert into tegs(idteg, tegname)values (50,'ukraine');